/**
 * Trusted temporal context (ADR 0010 fix): the model has no clock, so left to itself
 * it answers as if it were its training year — searching stale data and dating answers
 * wrong. We prepend a single trusted date line to EVERY cognitive system prompt (the
 * composer output AND the intent-router prompt, since the research search query is
 * generated by the router and must know the year too).
 *
 * The date is TRUSTED system context → it belongs in the system prompt, never the data
 * channel. Calling without `now` uses the local timezone; injected dates keep the
 * historical UTC label so existing deterministic tests remain byte-stable.
 */
export function temporalContext(now?: Date): string {
  if (now) {
    const utcDate = now.toISOString().slice(0, 10);
    return `Today's date is ${utcDate} (UTC).`;
  }

  const localNow = new Date();
  const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone || "local time";
  const year = localNow.getFullYear();
  const month = String(localNow.getMonth() + 1).padStart(2, "0");
  const day = String(localNow.getDate()).padStart(2, "0");
  return `Today's date is ${year}-${month}-${day} (${timeZone}).`;
}
