/**
 * Trusted temporal context (ADR 0010 fix): the model has no clock, so left to itself
 * it answers as if it were its training year — searching stale data and dating answers
 * wrong. We prepend a single trusted date line to EVERY cognitive system prompt (the
 * composer output AND the intent-router prompt, since the research search query is
 * generated by the router and must know the year too).
 *
 * The date is TRUSTED system context → it belongs in the system prompt, never the data
 * channel. `now` is injectable so tests are deterministic (default `new Date()`).
 */
export function temporalContext(now: Date = new Date()): string {
  return `Today's date is ${now.toISOString().slice(0, 10)} (UTC).`;
}
